### PR TITLE
License work under a CC BY-NC-SA 4.0 License

### PR DESCRIPTION
**Pull request by phijor**
See issue #22.

### CODE REVIEW

**Comment by phijor** [comment]
Ich überlege gerade, aber ja, das ist schlau.

**Comment by phijor** [comment]
Rebased on master, added license headers to new `.tex` files and squashed commits. This is ready to be fast-forward merged into master. Anyone care to review once again?

**Comment by LostInDarkMath** [comment]
Should the license be visible in the PDF files?

**Comment by phijor** [comment]
So there's the [`doclicense`](https://ctan.org/pkg/doclicense?lang=en) package which makes it trivial to include the license disclaimer in the `.pdf` files. Nice. Will add.

**Pull request merged**
